[variables]
# Nixpacks akan auto-detect PHP/Laravel.

[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "php83Extensions.pdo_sqlite", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.bcmath", "php83Extensions.gd", "php83Extensions.intl", "php83Extensions.opcache", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan optimize:clear"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
